### ISSUE TITLE
Items replacing as brushes

### ISSUE THREAD

**Issue by Kirilokaq** [Eroxen/MC-Paint-datapack#11]
Paper 1.21

When holding an item in the left hand and drawing, if F is pressed, the item gets replaced by a brush and the item will not come back

help

**Comment by Eroxen** [comment]
Thanks for your report! I cannot seem to reproduce this issue in Vanilla, so I'm afraid this can't be fixed. You'll just have to make sure to remove the item from your offhand before painting if you're using Paper.
