### ISSUE TITLE
how about a bedrock resource pack

### ISSUE THREAD

**Issue by trassert** [Eroxen/MC-Paint-datapack#14]
I have a server with a geyser, and when people with java put up pictures, bedrock users see it
If possible, will you make a resource pack for Bedrock? Thank you in advance

![photo_2024-12-18_21-05-56](https://github.com/user-attachments/assets/f30f19b1-641a-4cc4-bb74-94095f7222ae)

**Comment by Eroxen** [comment]
Hey there! There will not be support for Bedrock.
