### ISSUE TITLE
Brush duplication

### ISSUE THREAD

**Issue by WaxenSs** [Eroxen/MC-Paint-datapack#4]
Version: 1.3.0
Activate paint interface -> Put brush in container
-> Deactivate interface -> Activate paint interface.
You now have a brush in hand + a brush in a container.

**Comment by Eroxen** [comment]
This is a known thing, but it's not really an 'issue' since the Brush is otherwise a useless item. Therefore, trying to 'fix' this is not worth the effort and potential extra lag that such a fix may bring.

Thanks for your report!
