### ISSUE TITLE
MC paint 1.3.1 in MC 1.21 fabrik doesn’t work

### ISSUE THREAD

**Issue by alfonsico** [Eroxen/MC-Paint-datapack#7]
I am playing in local mode, Java 1.21 fabric 
The version 1.3.1 mod +data + data resources

aparentoy the system recognize the mod and says it’s installed but when I try to craft the brush it doesn’t work. It shown the pickaxe (3 wools plus 2 pale)

**Comment by Eroxen** [comment]
What do you mean by "crafting the brush"? The brush does not have a crafting recipe, you get it for free when you use the Studio

**Comment by alfonsico** [comment]
I got MC paint working in 1.20.1 forge. I craft the brush with three wools. However with fabric 1.21 version I can’t get the brush if I try to craft or in creative mode. Neither stamp. Not sure how to invoque the studio with “vanilla egg”

**Comment by Eroxen** [comment]
Are you using the mod called MCPaint: https://modrinth.com/mod/mcpaint ? This Github page is for a datapack, namely MC Paint: https://modrinth.com/datapack/mc-paint. You cannot craft the brush with three wool in this datapack.

**Comment by alfonsico** [comment]
Ok. I see I was a little confusing

the MC Paint mod is over forge 1.20.1 and I know how it works

the MC Paint data pack is over fabric 1.21 but I can’t do it work although it seems to be well installed

How could I do it after has been installed? Could you put the keys?

**Comment by Eroxen** [comment]
I am not sure what you mean? If you want to know how to use the datapack, you can read the description on Modrinth or the wiki on GitHub

**Comment by alfonsico** [comment]
Sorry but I’m bad en OTG for not understand how to make it work  “throwing an egg at a vanilla painting” drove me mad

“ The Studio is a block which lets you create custom paintings. It can be created by throwing an Egg at a vanilla painting, which grants the "True Tempera Paint" advancement.”

**Comment by Eroxen** [comment]
You take a painting (the normal Minecraft ones you craft with 1 wool and 8 sticks), place it on the wall, and then you throw an egg at it. Then if the datapack is installed, a little animation should play and you get the Studio.
